services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - /.env/
    volumes:
      - ./quiz_service:/service

    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DP_PASS=pass
    command:
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass