# Generated by Django 5.0.4 on 2024-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_remove_quiz_image_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
