# Generated by Django 5.0.4 on 2024-05-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_quiz_image_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
